"""fix user id fields

Revision ID: 51f66ad703c6
Revises: bc57a62dffa0
Create Date: 2024-03-25 23:31:13.365853

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '51f66ad703c6'
down_revision = 'bc57a62dffa0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('travel_access', 'user_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.BigInteger(),
                    existing_nullable=False)
    op.alter_column('travels', 'owner_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.BigInteger(),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('travels', 'owner_id',
                    existing_type=sa.BigInteger(),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    op.alter_column('travel_access', 'user_id',
                    existing_type=sa.BigInteger(),
                    type_=sa.INTEGER(),
                    existing_nullable=False)
    # ### end Alembic commands ###
