"""add User model

Revision ID: 6b7242cb4fab
Revises: 
Create Date: 2024-03-22 00:54:25.385405

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6b7242cb4fab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.Text(), nullable=True),
                    sa.Column('age', sa.Integer(), nullable=True),
                    sa.Column('city', sa.Text(), nullable=True),
                    sa.Column('country', sa.Text(), nullable=True),
                    sa.Column('bio', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
