"""add lat and lon to TravelLocation model

Revision ID: 708123c75bdc
Revises: ba9b385f9232
Create Date: 2024-03-25 01:54:20.196880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '708123c75bdc'
down_revision = 'ba9b385f9232'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travel_locations', sa.Column('latitude', sa.Text(), nullable=True))
    op.add_column('travel_locations', sa.Column('longitude', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('travel_locations', 'longitude')
    op.drop_column('travel_locations', 'latitude')
    # ### end Alembic commands ###
