"""add TravelAccess model

Revision ID: 7568fad7f2b1
Revises: 708123c75bdc
Create Date: 2024-03-25 02:59:12.304098

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7568fad7f2b1'
down_revision = '708123c75bdc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travel_access',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('travel_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['travel_id'], ['travels.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'travel_id'),
                    sa.UniqueConstraint('travel_id', 'user_id', name='_travel_user_uc')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('travel_access')
    # ### end Alembic commands ###
