"""add TravelLocation model

Revision ID: ba9b385f9232
Revises: be4a0cb6aac2
Create Date: 2024-03-24 21:11:18.807683

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ba9b385f9232'
down_revision = 'be4a0cb6aac2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travel_locations',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('city', sa.Text(), nullable=True),
                    sa.Column('start_date', sa.Date(), nullable=True),
                    sa.Column('end_date', sa.Date(), nullable=True),
                    sa.Column('travel_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['travel_id'], ['travels.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('travel_locations')
    # ### end Alembic commands ###
